### ISSUE TITLE
Crash while login.

### ISSUE THREAD

**Issue by bibiwise** [erikjjohnson/pwdsafe-iphone#15]
Hi Erik, after login everything seemed to be fine. I was adding a new file and the app crashed. Now I cannot open it anymore. Message: The passphrase is incorrect, but I know for sure it is correct.
How can I solve this? Please, urgent help required.
Thx.
Bibi

**Comment by erikjjohnson** [comment]
Hi @bibiwise, here is wiki on how to get your password safe file(s) off the device and loaded into another, compatible, app: https://github.com/erikjjohnson/pwdsafe-iphone/wiki/Getting-your-safes-out-of-the-app
