### ISSUE TITLE
Android version or can I convert my data to simple text?

### ISSUE THREAD

**Issue by interactivejoe** [erikjjohnson/pwdsafe-iphone#2]
I'm moving to an Android phone and need to somehow convert my data to text so I can put it in on my new Android phone. Any tips?

**Comment by erikjjohnson** [comment]
Yes, indeed, I have two suggestions, both follow a similar set of steps.

Step 1: Get the file that contains your passwords off of your iphone.  For this, you have two choices:

Choice 1: Upload the file to Dropbox.  To do this, in the iphone app, open your safe, then click the little gear icon at the bottom right of the screen.  Slide the slider for "Synchronize with DropBox" to on.  You will be asked to sign into DropBox, and then grab your .pwsafe file from there.

Choice 2: If you don't have a DropBox account, or don't want them to have your file, you can connect your device to a computer running iTunes.  (Like you would do to sync your iPhone).  In iTunes, click your iPhone device, then find the tab for Apps.  In the Apps tab, find PasswordSafes, then scroll down and you will see a Documents window (near the bottom, sometimes off screen).  Inside the documents window will be your .pwsafe file(s), just drag and drop them onto your computer's desktop or other folder)


Step 2: You can find a PasswordSafe app for android.  The PasswordSafe file my app writes is compatible with http://passwordsafe.sourceforge.net/ which has apps in the Google Play store (see the link).

Or, if you don't want that app, you can download the Desktop PasswordSafe application (same link as above), open your pwsafe file and in the export the passwords.  I used PasswordSafeSWT and it has File -> Export -> Plain text file

Good luck and congrats on the new phone!
