### ISSUE TITLE
Password Safe not syncing with Dropbox

### ISSUE THREAD

**Issue by jasong82** [erikjjohnson/pwdsafe-iphone#21]

**Comment by jasong82** [comment]
I am running IOS Version10.3.3 with the latests version of password safe and latest version of Dropbox. I am noticing that password safe is not syncing with dropbox. Each time I force a sync a screen showing authorizing is displayed until it timeouts. Could you please help me with this issue?

**Comment by erikjjohnson** [comment]
HI @jasong82, this is a known issue - https://github.com/erikjjohnson/pwdsafe-iphone/issues/10

I am not currently working on updating the latest Dropbox API, in fact, I'm not actively doing any updates to the code, so I don't expect this functionality to be restored.
