### ISSUE TITLE
Password stopped working 

### ISSUE THREAD

**Issue by cstyleelcano** [erikjjohnson/pwdsafe-iphone#22]
I followed the instructions on the other issues regarding this problem. When I try to drop it on my PC everything opens it encrypted. What next?

**Comment by Busher12** [comment]
My password stopped working on 2 different devices as well

**Comment by Busher12** [comment]
My coworker is now reporting to me that his password has stopped working as well

**Comment by erikjjohnson** [comment]
Hi all. I am sorry to hear of the troubles. I don't have any other suggestions, unfortunately, nor do I have any plans for updates to this app.
