### ISSUE TITLE
not accepting passcode

### ISSUE THREAD

**Issue by klchristylange** [erikjjohnson/pwdsafe-iphone#4]
I have been using the app on my iPhone for a few years and love it. I have four safes. They all have the same passphrase to get in. As of today, the main safe I use does not recognize the passphrase. I did not change it (don't know how to). I get "The passphrase is incorrect." Can I retrieve the passphrase? I can't figure out how it changed.

Kristen

**Comment by erikjjohnson** [comment]
Hi Kristen,

I'm sorry to hear about the troubles.  I don't have any way to restore a passphrase - the whole point of this app and similar apps is that me or others can't break into your safes.

However, I can suggest something to try.  You can try to get your safes off of your iPhone/iPad and onto a desktop/laptop computer.  Once on the desktop computer, you can use another PasswordSafe program that is compatible with the app to try to open the safes.  If there is something wrong with my program, or maybe a recently release of iOS, then maybe this approach would help.

Here are the steps you would need to take to try this solution:

1. Connect your iPhone/iPad to a laptop/desktop computer with a USB cable.
2. Open iTunes on the desktop
3. In iTunes, go to your phone, and then the Apps listing for your phone
4. Find the PasswordSafes app in the iTunes list for your phone and scroll down to the bottom where there is a list of "Documents" for the app
5. All four of your safes will be in the Documents list for the PasswordSafes app.
6. You can drag-and-drop your safes from the Documents list to your desktop
7. Once you have the safe files on your desktop, you can try to open them with this program: https://pwsafe.org/
