### ISSUE TITLE
64 bit 

### ISSUE THREAD

**Issue by dxwaldo** [erikjjohnson/pwdsafe-iphone#5]
Do you have any idea if you are going to make this app 64 bit?  Apple is giving a prompt that "this app may not work in future iOS releases" which come to find out has to do with 32 bit apps. 

I have used your app for several years and enjoy the simplicity and don't want to lose the ability to use it going forward. 

Thank you 
Tim

**Comment by erikjjohnson** [comment]
Hi Tim

Indeed I have been fretting about this for a few months.   Dropbox is also sending me notices that I need to update to their latest API. By way of explaination, not excuse, a few years back I lost access to the mac I needed to develop this on, but I know a few buddies I can ask.  I will check this week and see whether or not I can get a mac again and let you know either way.  Thanks for the reminder and sorry for the lack of updates in a long while

**Comment by erikjjohnson** [comment]
Hi Tim. Quick update. I struck a deal to borrow a mac on Monday. I will see then if this machine is capable or running the latest tools needed to properly compile and update the app

**Comment by erikjjohnson** [comment]
Hi Tim

I won't be able to update this app. I am sorry about that news. I too still use the app. When apple takes the app out of the store we will have to find an alternative. It is a long shot but perhaps someone else will take this code and put it into the store for us

**Comment by stokm** [comment]
Ok with IOS11.0 we are not able to use the app anymore. Is there a way to recovery the passwords from the old version? I mean the password are still in the data space of the app in the phone... am I right?

**Comment by mloizzi** [comment]
Been using this app for a long time.  Is there any way to recover the passwords?   Open the .psafe3 files?

Thanks in advance.
Michael

**Comment by erikjjohnson** [comment]
There is a longer thread here https://github.com/erikjjohnson/pwdsafe-iphone/issues/6 including how you can get your .psafe files, which you can open with any app from https://pwsafe.org/
