### ISSUE TITLE
I use Password Safes. I keep getting a warning that it needs to be updated to the new IOS or it will cease to work. Are you planning an update?

### ISSUE THREAD

**Issue by Busher12** [erikjjohnson/pwdsafe-iphone#6]

**Comment by erikjjohnson** [comment]
Hi, no, I don't have any plans to update the app.   I talked about why in [another issue](https://github.com/erikjjohnson/pwdsafe-iphone/issues/5), but the short answer is that I lost access to a Mac for development. 

For what it is worth I am sorry.  I too still use the app and I felt like I was doing a small bit of good in the world by paying to keep the app in the store, but while I was fine spending $100/year to keep the app in the store, I can't justify spending another $2000 for a mac.

**Comment by Busher12** [comment]
Thanks Erik, It’s a fantastic app and would gladly pay we have 3 huge fans of your app here. But I understand. I guess ill have to manually write them all down and reload them into something else. Appreciate your response.

**Comment by erikjjohnson** [comment]
Okay. I found a mac!  So I am going to download Xcode and try to recompile the app tonight

**Comment by Busher12** [comment]
That’s excellent news. Thank you so much. I hope its not too hard.

**Comment by erikjjohnson** [comment]
No worries.  I got the app recompiled using the latest tools.  I have several days of testing to see what breaks, but at least I am rolling again.  If it works, it will take another week or so for me to get it through the Apple store submission process.  I'll keep you posted.

**Comment by Busher12** [comment]
Great news thanks Erik.

**Comment by erikjjohnson** [comment]
As a quick update, I spent a few days attempting to debug and fix the underlying password safe code (that comes from another open source project) and I've finally decided to give up on that approach.  When I get some time, hopefully this weekend, I am going to attempt to get the latest version of the underlying code and see if I can get it to run.

**Comment by Busher12** [comment]
Thanks for the update. Wish I could help. Good Luck. We’re rooting for you.

**Comment by jonmlevine** [comment]
Need a hand?

**Comment by erikjjohnson** [comment]
Awesome. I didn't do anything tricky to make it a library.  In Xcode I created an archive/framework project, added the files from Passwordsafes core/ folder. I think the latest code calls this the Coreos/ folder

I did have to define one preprocessor value to prevent password safes from trying to inline assembly, but since you already got the code to compile I suspect you don't need that part

Did you get a lot of warnings during the compilation?  When I compiled the old code, because it was 32-bit code, it compiled but have many hundreds of warnings about pointer size casts

**Comment by jonmlevine** [comment]
I got a bunch of warnings about losing integer precision, but none relating to pointer manipulation -- they looked like they were all (or mostly) about converting 64 bit numbers to 32 bit ones.

**Comment by Busher12** [comment]
So your making progress?

**Comment by jonmlevine** [comment]
Well, I still haven't gotten the iOS application to compile.

**Comment by erikjjohnson** [comment]
I will try to check in what I have, that is compiling with similar warnings, tonight

**Comment by erikjjohnson** [comment]
I pushed a branch named ios64bit-update that compiles for me under Xcode 8.2.1 with a lot of warnings like you mentioned.   The app runs until the first real use of password safe library - for example creating a new entry then it crashes inside of the password safe library

**Comment by jonmlevine** [comment]
Thanks, Erik!  When I pull the branch and try to build it, it is still looking for some files in the thirdpartysource/PasswordSafe/corelib directory, specifically:

pwdsafe-iphone/thirdpartysource/PasswordSafe/corelib/BlowFish.cpp
pwdsafe-iphone/thirdpartysource/PasswordSafe/corelib/CheckVersion.cpp
pwdsafe-iphone/thirdpartysource/PasswordSafe/corelib/ItemField.cpp
pwdsafe-iphone/thirdpartysource/PasswordSafe/corelib/CoreImpExp.cpp

**Comment by erikjjohnson** [comment]
Oops. Forgot to commit the files. It should be fixed now

**Comment by jonmlevine** [comment]
Hi Erik. I think I fixed the problem.  Not a github expert but I think I committed the fix -- please check it out.

**Comment by erikjjohnson** [comment]
You're the best Jon.  I will try it out tomorrow when I can get at a mac

**Comment by jonmlevine** [comment]
Hmm, I'm not sure why it worked for me before but definitely not working now.

**Comment by jonmlevine** [comment]
Erik -- I forked the code and checked in a bunch of changes in my fork that compile mostly without warnings... I can now create a new safe, but when I add a new username & password to it, what gets written has some problem (it triggers an ASSERT in CItemData::Write).
I'll keep looking, but if you have some time you might also want to take a peek.

**Comment by erikjjohnson** [comment]
Thanks Jon.  I cannot get your fork to compile.  Oddly, the project claims that it cannot find Blowfish.cpp even though I can see it in thirdpartysource/PasswordSafe/corelib.  I'll try again and see if I can figure out what reference is wrong.

**Comment by jonmlevine** [comment]
I tried to check in again -- see if this works better

**Comment by jonmlevine** [comment]
Hi again Erik.  I commented out the assertion in CItemData::Write and now things seem to work when creating new files.  Haven't tried with an existing file yet.

**Comment by jonmlevine** [comment]
I was able to grab an existing safe from my iphone and it looks to open OK in the simulator, so maybe the assertion is checking something that doesn't need checking?

**Comment by jonmlevine** [comment]
Also, I deleted everything and checked out from my fork fresh, and it did compile, so I think the project files are all OK.

**Comment by Busher12** [comment]
HI, GUYS, 

Just checking in. Any progress on your development? Keep getting a warning that the current version wont work soon. Getting nervous. Should i start manually writing my passwords down?

**Comment by erikjjohnson** [comment]
It appears Jon solved it, I just have not got back to compiling it.

Regarding your passwords, you shouldn't need to write anything down.  To be safe:

1. Connect your device to a computer with iTunes
2. Select your device, then Apps
3. Find the PasswdSafes app and scroll down to the Documents pane for the App
4. In the documents pane you will find the actual "safe" (a file ending in .pwsafe) . Copy or drag and drop those files to your computer

You can open these files with any of the PasswordSafe clients from https://pwsafe.org/

**Comment by Busher12** [comment]
Great thanks again for your help and looking forward to the update

**Comment by erikjjohnson** [comment]
Jon's fixes correct the crashes seen earlier.  The code appears to have numerous non-crashing bugs now, likely due to changes of iOS.  For example, the settings don't seem to be read correctly, making the random password generator only generate one character. I'll have to start looking into them one at a time.  Thanks Jon!

**Comment by jonmlevine** [comment]
Erik, if you like, you can enumerate the bugs you see as individual issues -- we can try to divide and conquer.

**Comment by jonmlevine** [comment]
Created pull request #9

**Comment by jonmlevine** [comment]
Fixed the one character password generation problem.

**Comment by erikjjohnson** [comment]
Thanks Jon!  Sorry all for the delays on my side, I have not done a good job making time for this, but it is still on my list.  

Would it better for me to get out of the way and let someone else take the code and submit the app as I am falling behind?  If so, speak up.  I won't be offended.

**Comment by jonmlevine** [comment]
I'm happy to help more, but I'm not set up to submit apps

**Comment by jonmlevine** [comment]
Thanks for merging @erikjjohnson. Do we have more known bugs?

**Comment by erikjjohnson** [comment]
@jonmlevine do you want to tackle upgrading DropBox support - the API version/framework I used in the the past is set to expire in a few weeks?  Otherwise, we could just rip out DropBox.  I have several folks that have told me they like it (and I use it), but I have not looked into the difficulty of upgrading it.

**Comment by jonmlevine** [comment]
I opened issue #10 for this.

**Comment by jonmlevine** [comment]
@erikjjohnson, do we want to release this build with the current DropBox support (v1)? iOS 11 is coming out shortly.

**Comment by erikjjohnson** [comment]
yep.  I was working on cleaning up the 64-bit branch (removing the duplication of code to convert between strings/wide strings/and StringXs) before I merged it into master.  If you wanted to tackle that, that would be great.

**Comment by erikjjohnson** [comment]
Hi Jon.  I refactored the NSString/StringX code and merged ios64 branch into master.  Now I need to figure out how to get this into the AppStore, which is always more of a challenge then it should be.

**Comment by jonmlevine** [comment]
Anything I can do to help with that? iOS 11 day is here!

**Comment by erikjjohnson** [comment]
No, nothing can be done other than my time, unless you want to get a developer account and submit the app yourself.  At this point it is refreshing my developer certificates, getting the right artwork, testing on hardware, and hoping I don't need to get homeland security approval again because it uses crypto :(

**Comment by Busher12** [comment]
I have updated to the new IOS on my ipad and password safe no longer works. I am holding off on my phone so i can continue to use it. I have been following your progress and discussions. Just wondering when the new app will be available? Thanks for all your work

Sent from my iPad

**Comment by Barbie1959** [comment]
I updated my phone and now my PasswordSafe no longer works! HELP!! All of my password are being held hostage inside the app 😂
I’m following to see if I can get them released soon...thank you for all your hard work on updating this app! 😉

**Comment by Idaho1956** [comment]
So how can I get the data out of the app so I can at least print it off?  I see your directions from Aug 22 but I can't find the documents pane.

**Comment by erikjjohnson** [comment]
For the people still following the upgrade, it is still on my list.  I don't have a timeframe as this is stuck behind issues in my persona life that need attention more urgently.  Sorry.

**Comment by Barbie1959** [comment]
Thanks!  I will wait patiently ;)

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by 44aquach** [comment]
Hi @erikjjohnson is there a way to have this update pushed out asap.

I am no longer able to access any of my accounts. That's the reason why I relied on the app you created to keep me sane. It's been almost a month since the latest IOS 11 was released.
Is there a way to extract all of my passwords through a mac computer at least? 

I am in dire straits for access to this app.

Thank you.

**Comment by erikjjohnson** [comment]
@44aquach  I can't speed up my own time to get it done, sorry.  I know it is frustrating.  

Above in this thread you can find instructions for getting the password data off of your phone using iTunes and then you can get any number of compatible apps to read the data from https://pwsafe.org/

**Comment by 44aquach** [comment]
@erikjjohnson can you provide me an exact app/link where I can download because it looks like all the of apps on pwsafe.org is only compatible for Windows only which doesn't help me. I have a mac computer.
I am not going to purchase a windows computer just to extract my information.
Please help.

Thank you.

**Comment by erikjjohnson** [comment]
@44aquach  here is a link for all of the various apps: https://pwsafe.org/relatedprojects.shtml

And here is a Java version that I use on both Windows and Mac: https://sourceforge.net/projects/jpwsafe/

I have no affiliation with any of the apps listed.

**Comment by erikjjohnson** [comment]
For others watching this list, I was able to get the itunes store to accept the upload of this app this morning.  That does not mean I am out of the woods yet.  If the app is accepted, I have had this take between two days and two weeks.  If the app is rejected, I will have to deal with that when it happens

**Comment by Barbie1959** [comment]
👏🏻👏🏻thank you!

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by Busher12** [comment]
That’s great news Thanks for all your work.as you can see you have a lot of fans to your software

**Comment by OptimationClive** [comment]
Thanks Erik !

**Comment by Bushyzor** [comment]
I’m also eagerly awaiting the iOS 11 update! Been a daily user of the app since the beginning! Thanks for all the hard work Erik, really appreciate the effort!

**Comment by erikjjohnson** [comment]
Yay us!  Apple marked the app as ready for sale (after only two easily-fixed rejections late last Friday).  It should be in the store in a day or so.

**Comment by Busher12** [comment]
Erik, 
You have really saved fans of your app a ton of hassle. Cant thank you enough for all your hard work. I am sure its thankless. This app is the best because it does not require going out to some unsafe internet log in. I really think you should consider charging for this app and receive payment for your efforts. I and others i know that use it would gladly pay. Thanks again. Your app is outstanding

**Comment by erikjjohnson** [comment]
Please thank @jonmlevine who did the important work.  Also, I see version 3.0 in the store, so I will close this issue.  Feel free to open new issues for any other problems.

**Comment by Barbie1959** [comment]
Bless you all who worked on this update!  My passwords have been set free and I am one happy gal!! Bless you & Thank You again ❤️

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by jonmlevine** [comment]
I just upgraded to version 3.0 and iOS 11 and all is good.

Thanks a lot for this great tool @erikjjohnson !

**Comment by Barbie1959** [comment]
Erik,
I updated my password safe and it works now with the newest IOS update.  However, one of my saves (the one I use the most) isn’t responding to the 4 digit passcode.  All other dates have the same code and they all work.  That one closed and will not reopen.  I never changed the passcode and don’t even see that there is an option to change it.  I know there is no option to recover the passcode.  I am locked out of the one safe that has all my passwords..HELP!
Is there a way to fix this?
~Barb Ash :)

Get Outlook for iOS<https://aka.ms/o0ukef>

**Comment by Barbie1959** [comment]
Saves and dates should read “safes”!  Hate autocorrect.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________
From: Barbara A <barbie1959@hotmail.com>
Sent: Saturday, November 18, 2017 9:00:28 AM
To: reply@reply.github.com
Subject:

Erik,
I updated my password safe and it works now with the newest IOS update.  However, one of my saves (the one I use the most) isn’t responding to the 4 digit passcode.  All other dates have the same code and they all work.  That one closed and will not reopen.  I never changed the passcode and don’t even see that there is an option to change it.  I know there is no option to recover the passcode.  I am locked out of the one safe that has all my passwords..HELP!
Is there a way to fix this?
~Barb Ash :)

Get Outlook for iOS<https://aka.ms/o0ukef>

**Comment by MikeSampy** [comment]
Hi I updates mi iphone to 14.5.1 and can no longer open passwdsafes, can you help with this @erikjjohnson ? 

tnx
